language: node_js
node_js:
  - "5.5.0"

sudo: false

before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g protractor
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor e2e-tests/protractor-conf.js --browser=firefox
