# language: node_js
# node_js:
#   - "5.5.0"
#
# sudo: false
#
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - npm start > /dev/null &
#   - npm run update-webdriver
#   - sleep 3
#
# script:
#   - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
#   - node_modules/.bin/protractor e2e-tests/protractor-conf.js --browser=firefox
#
#
script:
  - npm test --single-run
  - node_modules/.bin/protractor public/javascripts/spec/e2e/conf.js --browser=firefox
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4.0.0"
before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g protractor
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - sleep 3
